### ISSUE TITLE
TypeError: '>' not supported between instances of 'NoneType' and 'dattime.dattime'

### ISSUE THREAD

**Issue by anotherfiz** [ZuinigeRijder/hyundai_kia_connect_monitor#48] opened 2023-02-17 20:21 UTC
**Describe the bug**
When I run python3.9 monitor.py I get this exception and no data output
TypeError: '>' not supported between instances of 'NoneType' and 'dattime.dattime'

Line 290 in handle_one_vehicle newest_updated_at max(dates)

**Versions**
* hyundai_kia_connect_monitor version: 35,36,37
* Python version: 3.9.5
* Operating System: Ubuntu 20.20
* Car: Hyundai
* Location: USA

**Comment by anotherfiz** [comment] 2023-02-17 20:36
This is my first time running the software, it seems like somewhere there is a comparison of dates occurring that assumes I've run it before, so it is attempting to compare against a NoneType. I'm trying to hunt it down.

**Comment by ZuinigeRijder** [comment] 2023-02-17 20:43
The latest version R3.7.0 does not have this statement at line 290.
But I imagine this is about these lines:

````
    last_updated_at = vehicle.last_updated_at
    location_last_updated_at = vehicle.location_last_updated_at
    dates = [last_updated_at, location_last_updated_at]
    newest_updated_at = max(dates)
````

Which version of [hyundai_kia_connect_api are you using](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/releases)? Because[ I tested with v2.4.0]([hyundai_kia_connect_api v2.4.0 here](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/releases)), as indicated in the README.

But I think something else is wrong and the following instance variables are not filled:

```
 last_updated_at: datetime.datetime = None
````

or 

````
@property
    def location_last_updated_at(self):
        """
        return last location datetime.
        last_updated_at and location_last_updated_at can be different.
        The newest of those 2 can be computed by the caller.
        """
        return self._location_last_set_time
````

Did you have monitor.cfg configured directly?
Is monitor.cfg in the same directory as were you run the script?

You can also try to run:

````
python debug.py
````

Does that give something back?

**Comment by anotherfiz** [comment] 2023-02-17 20:52
python debug.py works,

I have confirmed that monitor.py is crashing for me at this line 
```newest_updated_at = max(dates)```

the dates object is [datetime,None] going into the command above, I think the comparator is failing for that reason.

**Comment by ZuinigeRijder** [comment] 2023-02-17 20:57
Ok, so it looks like hyundai_kia_connect_api does not fill in Vehicle.py:

````
    return self._location_last_set_time
````

What car do you have and which country/region?

You can try to change the following statements:
````
    last_updated_at = vehicle.last_updated_at
    location_last_updated_at = vehicle.location_last_updated_at
    dates = [last_updated_at, location_last_updated_at]
    newest_updated_at = max(dates)
````

into (only second line is changed and made identical as last_updated_at):

````
    last_updated_at = vehicle.last_updated_at
    location_last_updated_at =  last_updated_at
    dates = [last_updated_at, location_last_updated_at]
    newest_updated_at = max(dates)
````

But that means there is no (GPS) location filled for your car.

**Comment by anotherfiz** [comment] 2023-02-17 20:59
Ioniq 5 in the USA, 

and thanks - we reached the same conclusion I think!

**Comment by ZuinigeRijder** [comment] 2023-02-17 21:02
Maybe there is something wrong in hyundai_kia_connect_api\HyundaiBlueLinkAPIUSA.py, for setting the location. I also have an IONIQ 5, but Europe. Codebase of hyundai_kia_connect_api is different, so maybe a bug in HyundaiBlueLinkAPIUSA.py?

You can also submit an issue in [hyundai_kia_connect_api](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api)?

**Comment by anotherfiz** [comment] 2023-02-17 21:04
Thank you for the suggestion, I will look into it!

**Comment by ZuinigeRijder** [comment] 2023-02-17 21:31
Interesting to know if only the location datetime is not filled, but longitude and latitude is filled. Maybe you are the first USA user and finding issues now. But always good to solve those. Probably the monitor tool is used only by Europe and probably using km instead of miles. Maybe we can find more issues. Glad to solve these with some help.

**Comment by anotherfiz** [comment] 2023-02-18 13:06
Happy to help in any way I can, let me know anything youd like me to test!

**Comment by ZuinigeRijder** [comment] 2023-02-18 20:43
It would be great if you could mail me the debug.py output (standard output and standard error). You can change some information for privacy if you want, e.g. VIN number and change latitude/longitude values into something else. The email address is a gmail.com address, the name of the github account without spaces before the @ sign ;-) Than I can compare the differences in output between Europe and USA. Maybe some interesting differences or error spotting is possible then. 

By the way, do you have in the Bluelink App also the possibility to show detailed consumption figures and trips. In Europe we have the option More ... -> My Trips. Actually dailystats.py is using this information, but currently only for Europe. Just wondering if this information is also available in the Bluelink app in USA.

**Comment by anotherfiz** [comment] 2023-02-19 13:50
Sent you an email with debug.txt

 >By the way, do you have in the Bluelink App also the possibility to show detailed consumption figures and trips. In Europe we have the option More ... -> My Trips. Actually dailystats.py is using this information, but currently only for Europe. Just wondering if this information is also available in the Bluelink app in USA.
 
 I do not seem to have access to this info, maybe its a USA thing? Maybe its because I have had data sharing turned off since I bought the car. I turned it back on and it says it will take 2 weeks to generate stats, so maybe there will be more available then. Stand by!

**Comment by ZuinigeRijder** [comment] 2023-02-20 09:08
@anotherfiz thanks for the information!
With this information I could find the root cause of the problem. 

The root cause is in the hyundai_kia_connect_api library.
In Vehicle.py _location_last_set_time is not correctly filled, only for EU this is done correctly.

Let's go step by step through the root cause.

related debug.py output, response from GET /ac/v2/rcs/rfc/findMyCar HTTP/1.1 (lat and lon are changed for privacy reasons if that was not already done)
````
{
  "head": 267,
  "coord": {
    "alt": 128,
    "lon": -79.1234567,
    "type": 0,
    "lat": 39.123456
  },
  "accuracy": {
    "pdop": 14,
    "hdop": 8
  },
  "time": "2023-02-19T14:15:24Z",
  "speed": {
    "unit": 1,
    "value": 0
  }
}
````

You see that "time" is filled with a date string.

In Vehicle.py is a setter, which fills the datetime type _location_last_set_time:
````
    _location_last_set_time: datetime.datetime = None

    @location.setter
    def location(self, value):
        self._location_latitude = value[0]
        self._location_longitude = value[1]
        self._location_last_set_time = value[2]
````

In KiaUvoApiEU.py this is datetime string is correctly converted to a datetime:
````
        if get_child_value(state, "vehicleLocation.coord.lat"):
            vehicle.location = (
                get_child_value(state, "vehicleLocation.coord.lat"),
                get_child_value(state, "vehicleLocation.coord.lon"),
                self.get_last_updated_at(
                    get_child_value(state, "vehicleLocation.time")
                ),
            )
````

However, in the other region implementations this is wrong, also in HyundaiBlueLinkAPIUSA.py:
````
vehicle.location = (
            get_child_value(state, "vehicleStatus.vehicleLocation.coord.lat"),
            get_child_value(state, "vehicleStatus.vehicleLocation.coord.lon"),
            get_child_value(state, "vehicleStatus.vehicleLocation.time"),
        )
````

You see the missing conversion to a datetime, e.g. which get_last_updated_at.
Note that the same is wrong for KiaUvoAPIUSA.py and KiaUvoApiCA.py.

Can you change in HyundaiBlueLinkAPIUSA.py those wrong lines into:
````
     if get_child_value(state, "vehicleStatus.vehicleLocation.coord"):
            vehicle.location = (
                get_child_value(state, "vehicleStatus.vehicleLocation.coord.lat"),
                get_child_value(state, "vehicleStatus.vehicleLocation.coord.lon"),
                self.get_last_updated_at(
                    get_child_value(state, "vehicleStatus.vehicleLocation.time")
                ),
            )
````

If this is the solution I can create an issue in hyundai_kia_connect_api and maybe even provide a Pull Request there.

**Comment by anotherfiz** [comment] 2023-02-20 22:51
I will Look into this ASAP

**Comment by anotherfiz** [comment] 2023-02-22 03:08
@ZuinigeRijder  I made the changes you requested and also modified monitor.py back to original, now seeing this issue

```20230221 22:02:07: Exception: expected string or bytes-like object
Traceback (most recent call last):
  File "/home/hyundai/hyundai_kia_connect_monitor/monitor.py", line 386, in handle_vehicles
    manager.update_all_vehicles_with_cached_state()  # needed >= 2.0.0
  File "/home/hyundai/hyundai_kia_connect_monitor/hyundai_kia_connect_api/VehicleManager.py", line 72, in update_all_vehicles_with_cached_state
    self.update_vehicle_with_cached_state(vehicle_id)
  File "/home/hyundai/hyundai_kia_connect_monitor/hyundai_kia_connect_api/VehicleManager.py", line 77, in update_vehicle_with_cached_state
    self.api.update_vehicle_with_cached_state(self.token, vehicle)
  File "/home/hyundai/hyundai_kia_connect_monitor/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py", line 352, in update_vehicle_with_cached_state
    self.get_last_updated_at(
  File "/home/hyundai/hyundai_kia_connect_monitor/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py", line 554, in get_last_updated_at
    m = re.match(r"(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})", value)
  File "/usr/lib/python3.9/re.py", line 191, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
```

**Comment by ZuinigeRijder** [comment] 2023-02-22 09:33
@anotherfiz thanks for testing.

I made a small test program to reproduce the error. There are 2 problems in get_last_updated_at:
- time can be None as input, and then the error: TypeError: expected string or bytes-like object
- the other datetime last_update_at string replaces characters before calling get_last_updated_at

I solved both by updating the method  get_last_updated_at inside HyundaiBlueLinkAPIUSA.py:
````
    def get_last_updated_at(self, value) -> dt.datetime:
        _LOGGER.debug(f"{DOMAIN} - last_updated_at - before {value}")
        if value is None:
            value = dt.datetime(2000, 1, 1, tzinfo=self.data_timezone)
        else:
            value = (
                value.replace("-", "")
                .replace("T", "")
                .replace(":", "")
                .replace("Z", "")
            )
            m = re.match(r"(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})", value)
            value = dt.datetime(
                year=int(m.group(1)),
                month=int(m.group(2)),
                day=int(m.group(3)),
                hour=int(m.group(4)),
                minute=int(m.group(5)),
                second=int(m.group(6)),
                tzinfo=self.data_timezone,
            )

        _LOGGER.debug(f"{DOMAIN} - last_updated_at - after {value}")
        return value
````

Today I will probably also push a new release of hyundai_kia_connect_monitor, which does not solve the root cause for hyundai_kia_connect_api (an issue/Pull Request when you checked this fix is actually working), but my tool can cope with None values too.

Can you test if replacing the method get_last_updated_at inside HyundaiBlueLinkAPIUSA.py works?

**Comment by anotherfiz** [comment] 2023-02-24 02:23
@ZuinigeRijder 

Made the modifications, and reverted monitor.py back, and still getting the NoneType error

```Traceback (most recent call last):
  File "/home/hyundai/hyundai_kia_connect_monitor/monitor.py", line 391, in handle_vehicles
    error = handle_one_vehicle(manager, vehicle, number_of_vehicles)
  File "/home/hyundai/hyundai_kia_connect_monitor/monitor.py", line 302, in handle_one_vehicle
    newest_updated_at = max(dates)
TypeError: '>' not supported between instances of 'NoneType' and 'datetime.datetime'
```

**Comment by ZuinigeRijder** [comment] 2023-02-24 07:06
@anotherfiz Thanks again for putting the effort in.
I think my corrections are correct, but that, unlike the EU version, in USA the vehicle.location is not always filled, e.g. because the times of calling findMyCar is restricted. This is also in the comment of HyundaiBlueLinkAPIUSA.py:

````
def get_location(self, token: Token, vehicle: Vehicle):
        r"""
        Get the location of the vehicle
        This logic only checks odometer move in the update.
        This call doesn't protect from overlimit as per:
        Only update the location if the odometer moved AND if the last location update
        was over an hour ago.
        Note that the "last updated" time is initially set to three hours ago.
        This will help to prevent too many calls to the API
        """
        url = self.API_URL + "rcs/rfc/findMyCar"
````

I suspect the USA implementation is thus differently, because in EU version you can ask the server for the cached server values and here it looks it actively asks for the location of the car now and then.

This means that 2 solutions are needed:
- you need to [upgrade to my latest version R3.8.0](https://github.com/ZuinigeRijder/hyundai_kia_connect_monitor/releases/tag/R3.8.0), because this will take care of not filled location_last_updated_at
- and I hope they [will approve the Pull Request for hyundai_kia_connect_api](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/286)  fixing the location_last_updated_at when this is called

Because you did already the local fixes in hyundai_kia_connect_api, you only need to upgrade to R3.8.0 and keep the local fixes in for now. I suspect that in monitor.csv the location latitude/longitude (will be shown as 0.0)/location_last_updated_at (last_updated_at will ne newer) are NOT filled in most of the time. I hope this will work for now.

Would be great if you mail me the monitor.csv after some days using it and also the updated output of debug.py (including standard error)

Hope these will be the solution, although I think I need to update the other python scripts to correct for "empty" locations. But that I can only do after I got some more data from your car in monitor.csv.

**Comment by ZuinigeRijder** [comment] 2023-02-25 13:01
New pull request because of merge:
https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/287

**Comment by ZuinigeRijder** [comment] 2023-02-25 20:36
@anotherfiz My hyundai_kia_connect_api Pull Request has been committed and is contained in release v3.1.1.

https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/releases/tag/v3.1.1 

Can you see if R3.8.0 works in combination with the above v3.1.1?
https://github.com/ZuinigeRijder/hyundai_kia_connect_monitor/releases/tag/R3.8.0

Thanks for any feedback.

**Comment by anotherfiz** [comment] 2023-02-26 23:00
Sorry for the late reply - I have run into another bug while testing!

```20230226 17:59:34: Exception: can't compare offset-naive and offset-aware datetimes
Traceback (most recent call last):
  File "/home/hyundai/hyundai_kia_connect_monitor/monitor.py", line 390, in handle_vehicles
    error = handle_one_vehicle(manager, vehicle, number_of_vehicles)
  File "/home/hyundai/hyundai_kia_connect_monitor/monitor.py", line 306, in handle_one_vehicle
    newest_updated_at = max(dates)
TypeError: can't compare offset-naive and offset-aware datetimes
```

**Comment by ZuinigeRijder** [comment] 2023-02-27 07:24
@anotherfiz My bad. In monitor.py and monitor_utils.py the timezone is not filled when datetime is None.

Can I ask another favor,  can you test with the following local changes.

monitor_utils.py (added timezone parameter):
````
def get_safe_datetime(date: datetime, tzinfo: timezone) -> datetime:
    """get safe datetime"""
    if date is None:
        return datetime(2000, 1, 1, tzinfo=tzinfo)
    return date
````

monitor.py (extra parameter vehicle.timezone):
````
    last_updated_at = get_safe_datetime(vehicle.last_updated_at, vehicle.timezone)
    location_last_updated_at = get_safe_datetime(
        vehicle.location_last_updated_at, vehicle.timezone
    )
````

This should fix this problem.

**Comment by ZuinigeRijder** [comment] 2023-02-27 20:26
@anotherfiz Damned, thought this was the fix. Can you mail me the output of debug.py, including standard error?

**Comment by ZuinigeRijder** [comment] 2023-02-27 20:32
I think anonymized debug.py output would help me, because I am also interested in vehicle.timezone.

**Comment by anotherfiz** [comment] 2023-02-27 20:39
emailed it to you

**Comment by ZuinigeRijder** [comment] 2023-02-27 20:44
Thanks. Unfortunately the timezone is None, so that is the problem.
````
    last_updated_at=datetime.datetime
        (
            2023,
             2,
             27,
             20,
             24,
             30,
             tzinfo=datetime.timezone.utc
        ),
    timezone=None,
````

I would expect timezone utc, instead of None. I am going to dig into hyundai_kia_connect_api again.

**Comment by ZuinigeRijder** [comment] 2023-02-28 07:34
@anotherfiz Apparently Vehicle.timezone is not consistent used. Only in KiaUvoApiCA.py this is set, in the other implementations HyundaiBlueLinkAPIUSA.py, KiaUvoApiEU.py and KiaUvoAPIUSA.py these are NOT initialized when Vehicle is instantiated, while internally they use UTC.

You can easily fix this locally by changing the default timezone in Vehicle.py line 95:

Change:
````
timezone: datetime.timezone = None
```` 

Into:
````
timezone: datetime.timezone = datetime.timezone.utc  # default UTC
````

Further looking at the location_last_updated_at, I am still wondering why this datetime is not filled (None), so probably there is still something wrong in HyundaiBlueLinkAPIUSA.py, because in debug.py I see 'time' is filled there. So it should have a location_last_updated_at in the situations when findMyCar was called!

First, in the following get_cached_vehicle_status response you see only the VehicleLocation 'lat' and 'lon', not 'time' (I did a pretty print):
````
DEBUG:hyundai_kia_connect_api.HyundaiBlueLinkAPIUSA:hyundai_kia_connect_api - get_cached_vehicle_status response {
  "hataTID": "zqCe14XFQhOQHksA6zYsZA",
  "vehicleStatus": {
    "dateTime": "2023-02-27T20:24:30Z",
    "acc": false,
    "defrostStatus": "false",
    "transCond": true,
    "doorLockStatus": "false",
    "doorOpen": {
      "frontRight": 0,
      "frontLeft": 0,
      "backLeft": 0,
      "backRight": 0
    },
    "washerFluidStatus": false,
    "battery": {
      "batSoc": 80,
      "sjbDeliveryMode": 1
    },
    "hazardStatus": 0,
    "vehicleLocation": {
      "coord": {
        "lon": -79.123456,
        "type": 0,
        "lat": 39.123456
      }
    },
....
````

Thereafter a call is done, using findMyCar , where 'time' is available:
````
DEBUG:urllib3.connectionpool:https://api.telematics.hyundaiusa.com:443 "GET /ac/v2/rcs/rfc/findMyCar HTTP/1.1" 200 None
DEBUG:hyundai_kia_connect_api.HyundaiBlueLinkAPIUSA:hyundai_kia_connect_api - Get Vehicle Location {
  "head": 267,
  "coord": {
    "alt": 0,
    "lon": -79.123456,
    "type": 0,
    "lat": 39.123456
  },
  "accuracy": {
    "pdop": 14,
    "hdop": 8
  },
  "time": "2023-02-27T20:33:27Z",
  "speed": {
    "unit": 1,
    "value": 0
  }
}
````

And there I think I spotted the problem, why location_last_updated_at is not filled. 
There are two state entries in the dictionary:
- vehicleStatus.vehicleLocation (filled by get_cached_vehicle_status response)
- vehicleLocation (filled by _get_vehicle_location)

So _update_vehicle_properties should check first vehicleLocation , then vehicleStatus.vehicleLocation. Something like:

````
if get_child_value(state, "vehicleLocation.coord.lat"):
            vehicle.location = (
                get_child_value(state, "vehicleLocation.coord.lat"),
                get_child_value(state, "vehicleLocation.coord.lon"),
                self.get_last_updated_at(
                    get_child_value(state, "vehicleLocation.time")
                ),
            )
        elif get_child_value(state, "vehicleStatus.vehicleLocation.coord.lat"):
            vehicle.location = (
                get_child_value(state, "vehicleStatus.vehicleLocation.coord.lat"),
                get_child_value(state, "vehicleStatus.vehicleLocation.coord.lon"),
                self.get_last_updated_at(
                    get_child_value(state, "vehicleStatus.vehicleLocation.time")
                ),
            )
````

I will send you a mail with HyundaiBlueLinkAPIUSA.py version, with this change, so you can check if this is the real solution. If that is true, I can create a new Pull Request for hyundai_kia_connect_api for solving this specific problem.

**Comment by ZuinigeRijder** [comment] 2023-02-28 09:06
I created a Pull Request already, assuming my changes are correct.

https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/288

**Comment by anotherfiz** [comment] 2023-02-28 19:46
With your vehicle.py change and no other changes I still get the issue.  eg, just 

```timezone: datetime.timezone = None```
to
```timezone: datetime.timezone = datetime.timezone.utc  # default UTC```

I am still getting the same issue. I alluded to this in my last comment before sending the debug - Are we completely sure that in

```2023-02-28 19:33:54**+00:00**     2000-01-01 00:00:00``` 

the bolded offset is a result of timezone or specifically the type of date-time being parsed. You are the expert, but it is strange to me that the datetime on the right above does not also have a +XX:XX with values that would indicate the different time zone.  Wish I could be of more help, but that is the only thing I can see that would obviously fail a compare, because it does not have all the same components. also the debug output

```20230228 14:42:02: Exception: can't compare offset-naive and offset-aware datetimes
Traceback (most recent call last):
  File "/home/hyundai/hyundai_kia_connect_monitor/monitor.py", line 392, in handle_vehicles
    error = handle_one_vehicle(manager, vehicle, number_of_vehicles)
  File "/home/hyundai/hyundai_kia_connect_monitor/monitor.py", line 308, in handle_one_vehicle
    newest_updated_at = max(dates)
**TypeError: can't compare offset-naive and offset-aware datetimes**```

**Comment by anotherfiz** [comment] 2023-02-28 19:52
Actually, in debug it still says  timezone = None

I wonder if I have done something wrong. when I get home I will re-clone and re-setup and test again

**Comment by ZuinigeRijder** [comment] 2023-02-28 21:12
Maybe you should remove the __pycache__ directories, so they get recompiled?

**Comment by anotherfiz** [comment] 2023-02-28 22:52
Cloned new code base and made changes to vehicle.py - still the same error =(

**Comment by ZuinigeRijder** [comment] 2023-03-01 09:54
@anotherfiz This is a real puzzle. I hope that you are still enjoying it together with me in solving the puzzle?
Especially that vehicle.timezone is None bothers me. What could be the cause? Because in Vehicle.py you did set it locally to utc and in ApiImpl.py it is also defualt utc. So that would mean that in one way or another HyundaiBlueLinkAPIUSA.py resets it to None.

Just to be sure, you did NOT install (ever) hyundai_kia_connect_api [and always copied hyundai_kia_connect_api subfolder to hyundai_kia_connect_monitor](https://github.com/ZuinigeRijder/hyundai_kia_connect_monitor#how-to-install-python-packages-and-hyundai_connect_monitor)? Because it could be that than the local hyundai_kia_connect_api  version is not taken, but the installed one?

````
Extract both and move the hyundai_kia_connect_api subfolder of hyundai_kia_connect_api-[version] under hyundai_kia_connect_monitor.
````

Can you try also with more logging in debug.py (I printed e.g. timezone just after instantiation of VehicleManager) and mail me the anonymized results:
````
vm = VehicleManager(
    region=int(REGION),
    brand=int(BRAND),
    username=USERNAME,
    password=PASSWORD,
    pin=PIN,
)
for KEY in vm.vehicles:
    VEHICLE = vm.vehicles[KEY]
    print(f"timezone: {VEHICLE.timezone}")
    print(f"vehicle: {VEHICLE}")

vm.check_and_refresh_token()
vm.update_all_vehicles_with_cached_state()  # needed >= 2.0.0

for KEY in vm.vehicles:
    VEHICLE = vm.vehicles[KEY]
    print(f"timezone: {VEHICLE.timezone}")
    print(f"Last updated at: {VEHICLE.last_updated_at}")
    print(f"Location Last updated at: {VEHICLE.location_last_updated_at}")
    print(f"Location: {VEHICLE.location}")
    print(f"vehicle: {VEHICLE}")

print(type(vm.vehicles))
print(vm.vehicles)
print("Pretty print vm.vehicles:")
print_indented(str(vm.vehicles))
print_info(vm.vehicles)
````

**Comment by ZuinigeRijder** [comment] 2023-03-09 15:09
@anotherfiz There is a new release 3.1.3 with my solution and also with more debug logging, so you can try that:
https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/releases/tag/v3.1.3

**Comment by anotherfiz** [comment] 2023-03-09 21:25
@ZuinigeRijder Sorry I ghosted for a little bit - life gets busy!

To loop back:  I did not ever install the connect API, simply copied it to the monitor folder as instructed.

Sadly, the same error still exists, and in debug output timezone still set to 'None'

```         last_updated_at=datetime.datetime
        (
            2023,
             3,
             9,
             21,
             24,
             29,
             tzinfo=datetime.timezone.utc
        ),
         timezone=None,
```

**Comment by ZuinigeRijder** [comment] 2023-03-10 08:02
@anotherfiz I definitely overlook something. Can you mail me the full debug output with privacy applied? Because I added extra debug logging in 3.1.3.

**Comment by anotherfiz** [comment] 2023-03-15 19:29
Did you get the debug.txt?

**Comment by ZuinigeRijder** [comment] 2023-03-15 19:55
Yes, thanks. I am still puzzling and have looked several times to debug.txt. I will come back to you in a couple of days.

**Comment by anotherfiz** [comment] 2023-03-16 20:49
For your situational awareness there was just a huge update to the hyundai bluelink app in the USA today - it now shows way more information regarding trip details

**Comment by ZuinigeRijder** [comment] 2023-03-17 09:29
> For your situational awareness there was just a huge update to the hyundai bluelink app in the USA today - it now shows way more information regarding trip details

Ah, probably that means that the same sort of tripinfo might be accessible, which I made available for Europe in hyundai_kia_connect_api. See this issue: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/issues/248

Actually, I had to sniff the bluelink calls for Europe, to know what the requests and responses were:

**How to sniff**

For the ones who also want to be able to sniff the calls from the App, this is how I did it (do it at your own risk):

- Installed NoxPlayer emulator in Windows 10 and emulate Android 5
- Installed Burp Suite Community Edition on Windows 10
- Then followed this guide without installing Bluelink App yet: [Android App Traffic Decryption using Nox Player - Windows Guide](https://archive.ph/k1hIG)
- Disabled Root (because Bluelink App will not work on rooted device) and proxy in Android emulator, installed Bluelink App and login with my credentials (with proxy I could not login?)
- Enabled proxy and opened Bluelink App and in the Burp Suite the decoded https requests/responses were available

Someone with bluelink in USA having time and knowledge, could find out the requests/responses, so those could be added.

**Comment by ZuinigeRijder** [comment] 2023-03-18 13:33
> Did you get the debug.txt?

Yes, I emailed you back today, with another experiment.

**Comment by ZuinigeRijder** [comment] 2023-03-18 13:35
> For your situational awareness there was just a huge update to the hyundai bluelink app in the USA today - it now shows way more information regarding trip details

Someone else also submitted an issue to hyundai_kia_connect_api, I responded on that: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/issues/299#issuecomment-1474400685

**Closed** 2023-11-02 11:58 UTC
